// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmqEs9rcKa1iQj_mvFa7h1Jlel0Kega3c',
    appId: '1:681082286778:web:ce2fcf187ca42d575a4883',
    messagingSenderId: '681082286778',
    projectId: 'quiz-making-app',
    authDomain: 'quiz-making-app.firebaseapp.com',
    storageBucket: 'quiz-making-app.appspot.com',
    measurementId: 'G-H82WZH62CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCbc4QuO_Wj3EfDptqbTRASQkMQjAFEEI',
    appId: '1:681082286778:android:b2132351b74ac5a85a4883',
    messagingSenderId: '681082286778',
    projectId: 'quiz-making-app',
    storageBucket: 'quiz-making-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV68gYGZzWkuSaVEItAqA-6dRLq9tQPZ0',
    appId: '1:681082286778:ios:9b15bb03380a6fd65a4883',
    messagingSenderId: '681082286778',
    projectId: 'quiz-making-app',
    storageBucket: 'quiz-making-app.appspot.com',
    iosClientId: '681082286778-s8qbpb8s7ct71sohdvb9kuql6tlbfa96.apps.googleusercontent.com',
    iosBundleId: 'com.example.chapter3StatefullWidgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV68gYGZzWkuSaVEItAqA-6dRLq9tQPZ0',
    appId: '1:681082286778:ios:aceb841d1bebb7ee5a4883',
    messagingSenderId: '681082286778',
    projectId: 'quiz-making-app',
    storageBucket: 'quiz-making-app.appspot.com',
    iosClientId: '681082286778-30dqs1inmj4l2j54il26i2c5tqhrsqd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chapter3StatefullWidgets.RunnerTests',
  );
}
